template_project/template_app/urls.py
from django.conf.urls import url
from template_app import views

# TEMPLATE TAGGING
app_name = 'happy_app'

urlpatterns = [
    url(r'^relative/$', views.relative, name='relative'),
    url(r'^other/$', views.other, name='other'),

]

template_project/template_project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from template_app import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url('admin/', admin.site.urls),
    url(r'^template_app/', include('template_app.urls'))
]

template_project/template_app/models.py
from django.db import models

# Create your models here.

template_project/template_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = { 'text':'hello world', 'number':2020}
    return render(request, 'template_app/index.html',context=context_dict)


def other(request):
    return render(request, 'template_app/other.html')


def relative(request):
    return render(request, 'template_app/relative_url_templates.html')

template_project/templates/template_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">    <meta charset="utf-8">

  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li ><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li ><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
          <li ><a class="navbar-link" href="{% url 'happy_app:other' %}">OTHER</a></li>

        </ul>

      </div>
    </nav>

    <div class="container">
      {% block body_block %}
        <!-- anything outside of this will be inherited if you extend!!! -->
      {% endblock %}
    </div>


  </body>
</html>

template_project/templates/template_app/index.html
<!DOCTYPE html>
{% extends "template_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h2>{{ text|cut:'world' }}</h2>
    <h3>{{ number|add:"99" }}</h3>

  {% endblock %}

template_project/templates/template_app/other.html
<!DOCTYPE html>
{% extends "template_app/base.html" %}
  {% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an exapmple of template inheritance!</h2>
  {% endblock %}

template_project/templates/template_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RELATIVE</title>
  </head>
  <body>
    <h1>WELCOME TO RELATIVE URL TEMPLATES</h1>
    <a href="{% url 'happy_app:other' %}">THE OTHER PAGE</a><br>
    <a href="{% url 'admin:index' %}">ADMIN PAGE</a><br>
    <a href="{% url 'index' %}">INDEX PAGE</a>
  </body>
</html>